### ISSUE TITLE
Unable to `GET` datasets from 0.4.0 branch

### ISSUE THREAD

**Issue by dvince2** [DARPA-ASKEM/data-service#230]
After creating a new dataset and uploading a CSV via signed url, I am unable to `Get` datasets from the endpoint - an error 500 is returned
```
curl -X 'GET' \
  'http://localhost:3020/datasets?page_size=100&page=0' \
  -H 'accept: application/json'
```

logs:
```
INFO:     192.168.65.4:53950 - "GET / HTTP/1.1" 200 OK
INFO:     192.168.65.4:53950 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     192.168.65.4:51440 - "GET /datasets?page_size=100&page=0 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/api/./tds/modules/dataset/controller.py", line 53, in list_datasets
    content=jsonable_encoder(dataset_response(res["hits"]["hits"])),
  File "/api/./tds/modules/dataset/response.py", line 11, in dataset_response
    return [Dataset(**hit["_source"]) for hit in es_list]
  File "/api/./tds/modules/dataset/response.py", line 11, in <listcomp>
    return [Dataset(**hit["_source"]) for hit in es_list]
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Dataset
username
  none is not an allowed value (type=type_error.none.not_allowed)
file_names
  none is not an allowed value (type=type_error.none.not_allowed)
```

**Comment by toddroper** [comment]
This error is most likely related to datasets that were previously created.  We need to set the username to optional until we decide on how the user and project identifiers will be handled.  The file_names array will need to be updated in ES or you can delete the previous datasets.

**Comment by toddroper** [comment]
Issue is with Dataset post validation.  Related to #239 

Closing.
