### ISSUE TITLE
0.4.0 - Cannot pull a project with a model in it?

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/data-service#235]
GET /projects/{id} throws a validation error

Steps done:
1) Created model based off of swagger example:
```
{
    "id": "1eec18fc-a0bc-47a0-bff9-f85e31788e8c",
    "timestamp": "2023-06-07T13:52:22.198000+00:00",
    "name": "A Test Model",
    "description": "Test Model Post from Swagger.",
    "schema": "https://raw.githubusercontent.com/DARPA-ASKEM/Model-Representations/petrinet_v0.2/petrinet/petrinet_schema.json",
    "model_version": "1.0"
  }
  
```
  
2)  created new project

3) ran the GET /projects/{id}

Logs:
```
INFO:     172.22.0.1:56892 - "GET /projects/2 HTTP/1.1" 500 Internal Server Error
2023-06-07 11:00:37 data-service-api              | ERROR:    Exception in ASGI application
2023-06-07 11:00:37 data-service-api              | Traceback (most recent call last):
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
2023-06-07 11:00:37 data-service-api              |     result = await app(  # type: ignore[func-returns-value]
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2023-06-07 11:00:37 data-service-api              |     return await self.app(scope, receive, send)
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
2023-06-07 11:00:37 data-service-api              |     await super().__call__(scope, receive, send)
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
2023-06-07 11:00:37 data-service-api              |     await self.middleware_stack(scope, receive, send)
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2023-06-07 11:00:37 data-service-api              |     raise exc
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2023-06-07 11:00:37 data-service-api              |     await self.app(scope, receive, _send)
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
2023-06-07 11:00:37 data-service-api              |     await self.app(scope, receive, send)
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
2023-06-07 11:00:37 data-service-api              |     raise exc
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
2023-06-07 11:00:37 data-service-api              |     await self.app(scope, receive, sender)
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2023-06-07 11:00:37 data-service-api              |     raise e
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2023-06-07 11:00:37 data-service-api              |     await self.app(scope, receive, send)
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
2023-06-07 11:00:37 data-service-api              |     await route.handle(scope, receive, send)
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
2023-06-07 11:00:37 data-service-api              |     await self.app(scope, receive, send)
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
2023-06-07 11:00:37 data-service-api              |     response = await func(request)
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
2023-06-07 11:00:37 data-service-api              |     raw_response = await run_endpoint_function(
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
2023-06-07 11:00:37 data-service-api              |     return await run_in_threadpool(dependant.call, **values)
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2023-06-07 11:00:37 data-service-api              |     return await anyio.to_thread.run_sync(func, *args)
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
2023-06-07 11:00:37 data-service-api              |     return await get_asynclib().run_sync_in_worker_thread(
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
2023-06-07 11:00:37 data-service-api              |     return await future
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
2023-06-07 11:00:37 data-service-api              |     result = context.run(func, *args)
2023-06-07 11:00:37 data-service-api              |   File "/api/./tds/routers/projects.py", line 71, in get_project
2023-06-07 11:00:37 data-service-api              |     return Project.from_orm(project, list(parameters))
2023-06-07 11:00:37 data-service-api              |   File "/api/./tds/schema/project.py", line 28, in from_orm
2023-06-07 11:00:37 data-service-api              |     return super().from_orm(body)
2023-06-07 11:00:37 data-service-api              |   File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 579, in from_orm
2023-06-07 11:00:37 data-service-api              |     raise validation_error
2023-06-07 11:00:37 data-service-api              | pydantic.error_wrappers.ValidationError: 1 validation error for Project
2023-06-07 11:00:37 data-service-api              | assets -> ResourceType.models -> 0
2023-06-07 11:00:37 data-service-api              |   value is not a valid integer (type=type_error.integer)
2023-06-07 11:03:52 data-service-api              | INFO:     172.22.0.1:38356 - "GET /models/descriptions?page_size=100&page=0 HTTP/1.1" 200 OK
```

**Comment by toddroper** [comment]
This issue is related to the project asset ID expecting an integer.  This should be resolved when the workflow updates get merged in.
